prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 2d  # Reduced from 30d to 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3  # Cheaper than gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi  # Reduced from 50Gi

grafana:
  enabled: true
  adminPassword: admin123
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    storageClassName: gp3  # Cheaper than gp2
    size: 5Gi  # Reduced from 10Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3  # Cheaper than gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi  # Reduced from 10Gi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

defaultRules:
  create: true