apiVersion: v1
kind: ConfigMap
metadata:
  name: travel-webapp-config
  namespace: travel-webapp
data:
  app.name: "Travel Webapp"
  app.properties: |
    app.version=1.0.0
    environment=production
    log.level=info
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
        location /health {
            access_log off;
            return 200 "healthy\n";
        }
    }