apiVersion: v1
kind: ServiceAccount
metadata:
  name: travel-webapp-sa
  namespace: travel-webapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: travel-webapp
  name: travel-webapp-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travel-webapp-rolebinding
  namespace: travel-webapp
subjects:
- kind: ServiceAccount
  name: travel-webapp-sa
  namespace: travel-webapp
roleRef:
  kind: Role
  name: travel-webapp-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: travel-webapp-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: travel-webapp-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: travel-webapp-sa
  namespace: travel-webapp
roleRef:
  kind: ClusterRole
  name: travel-webapp-cluster-role
  apiGroup: rbac.authorization.k8s.io